"""Test fixtures shared across every test file.

The EDF fixture is generated by the SkyBrain SDK's own CLI
(`skybrain-generate-edf`) — see docs/CLI_REFERENCE.md in the BCI Studio docs.
If the CLI isn't on PATH, the fixture skips with a clear message: that's our
contract for the `[sdk]` extra (SDK is optional, adapter tests require it).
"""

from __future__ import annotations

import os
import shutil
import subprocess
from collections.abc import Iterator
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from service.main import create_app


@pytest.fixture(scope="session")
def app_audit_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A temp audit directory so tests don't pollute the repo root."""
    audit_dir = tmp_path_factory.mktemp("audit")
    os.environ["SKYBRAIN_QVAC_AUDIT_DIR"] = str(audit_dir)
    return audit_dir


@pytest.fixture(scope="session")
def client(app_audit_dir: Path) -> Iterator[TestClient]:  # env side effect via fixture
    """FastAPI TestClient shared across tests in a session.

    The audit-dir fixture is depended on so the env var is set before the app
    boots and reads `Settings`.
    """
    app = create_app()
    with TestClient(app) as c:
        yield c


@pytest.fixture(scope="session")
def sample_edf(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Generate a small EDF via `skybrain-generate-edf` for tests.

    Skipped if the SDK CLI isn't installed (matches our optional-SDK dependency
    contract). Falls back to `skybrain-generate` if the single-file generator
    is missing.
    """
    if shutil.which("skybrain-generate-edf") is None and shutil.which("skybrain-generate") is None:
        pytest.skip(
            'skybrain SDK CLI not on PATH; install via `pip install -e ".[sdk]"` '
            "to enable adapter tests."
        )

    out_dir = tmp_path_factory.mktemp("edf")

    if shutil.which("skybrain-generate-edf") is not None:
        # --output is a path PREFIX, not a full filename (per `skybrain-generate-edf --help`).
        # Target the documented latency-budget scenario: 30s total, 4ch — small
        # enough to run plan §6's <200ms biomarker budget on the test runner.
        # Explicit pre/post override the 60s absolute defaults (the help text
        # says "40% of total" but the actual default is 60s either way).
        out_prefix = out_dir / "sample"
        result = subprocess.run(
            [
                "skybrain-generate-edf",
                "--output",
                str(out_prefix),
                "--duration",
                "30",
                "--channels",
                "4",
                "--pre-duration",
                "10",
                "--post-duration",
                "10",
            ],
            capture_output=True,
            text=True,
            timeout=60,
            check=False,
        )
        if result.returncode == 0:
            candidates = sorted(out_dir.glob("**/*.edf"))
            if candidates:
                return candidates[0]
        # Fall through to multi-scenario generator on failure.

    # Multi-scenario fallback. Use defaults (180s total) so pre+post budget fits.
    result = subprocess.run(
        [
            "skybrain-generate",
            "--scenarios",
            "relaxation",
            "--output",
            str(out_dir),
        ],
        capture_output=True,
        text=True,
        timeout=180,
        check=False,
    )
    if result.returncode != 0:
        pytest.skip(
            f"skybrain-generate failed (rc={result.returncode}): "
            f"stdout={result.stdout!r} stderr={result.stderr!r}"
        )

    candidates = sorted(out_dir.glob("**/*.edf"))
    if not candidates:
        pytest.skip(f"skybrain-generate produced no EDF files in {out_dir}")
    return candidates[0]
