"""POST /v1/eeg/biomarkers end-to-end tests.

Every test uses a real EDF generated by the SDK's own CLI — no synthetic data,
no mocked adapter. Tests are skipped at the conftest level if the SDK isn't
installed; if you're seeing them skip in CI, the runner is missing the [sdk]
extra.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from fastapi.testclient import TestClient


@pytest.mark.sdk
def test_biomarkers_spectral_returns_payload(
    client: TestClient,
    sample_edf: Path,
) -> None:
    response = client.post(
        "/v1/eeg/biomarkers",
        json={
            "session_file": str(sample_edf),
            "biomarker_set": "spectral",
            "profile": "skybrain_4ch",
        },
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["modality"] == "eeg"
    assert body["biomarker_set"] == "spectral"
    assert body["kind"] == "features"
    assert isinstance(body["payload"], dict)
    assert len(body["input_sha256"]) == 64
    assert body["latency_ms"] >= 0.0


@pytest.mark.sdk
def test_biomarkers_qc_returns_qc_kind(
    client: TestClient,
    sample_edf: Path,
) -> None:
    response = client.post(
        "/v1/eeg/biomarkers",
        json={
            "session_file": str(sample_edf),
            "biomarker_set": "qc",
        },
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["kind"] == "qc"


@pytest.mark.sdk
def test_biomarkers_full_runs_under_latency_budget(
    client: TestClient,
    sample_edf: Path,
) -> None:
    """Plan §6 latency budget: <200 ms on a 30-second window for biomarkers.

    The fixture is a 30 s recording. We allow 2× headroom (400 ms) on CI
    runners since they're not always cold-cache-friendly; the strict budget
    holds for production benchmarking.
    """
    response = client.post(
        "/v1/eeg/biomarkers",
        json={
            "session_file": str(sample_edf),
            "biomarker_set": "full",
        },
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert (
        body["latency_ms"] < 400.0
    ), f"biomarker compute exceeded 2x latency budget: {body['latency_ms']}ms"


def test_biomarkers_rejects_missing_file(client: TestClient) -> None:
    response = client.post(
        "/v1/eeg/biomarkers",
        json={
            "session_file": "/tmp/definitely-does-not-exist.edf",
            "biomarker_set": "spectral",
        },
    )
    assert response.status_code == 404
    body = response.json()
    assert body["detail"]["error"]["code"] == "recording_not_found"


def test_biomarkers_rejects_unknown_biomarker_set(client: TestClient) -> None:
    response = client.post(
        "/v1/eeg/biomarkers",
        json={
            "session_file": "/tmp/anything.edf",
            "biomarker_set": "telekinesis",
        },
    )
    # Pydantic enum validation kicks in before the file check.
    assert response.status_code == 422


@pytest.mark.sdk
def test_biomarkers_summary_view_smaller_than_detailed(
    client: TestClient,
    sample_edf: Path,
) -> None:
    """Summary view drops per-window time series; should always be smaller."""
    body = {"session_file": str(sample_edf), "biomarker_set": "spectral"}

    summary_resp = client.post(
        "/v1/eeg/biomarkers",
        json={**body, "view": "summary"},
    )
    detailed_resp = client.post(
        "/v1/eeg/biomarkers",
        json={**body, "view": "detailed"},
    )
    assert summary_resp.status_code == 200, summary_resp.text
    assert detailed_resp.status_code == 200, detailed_resp.text

    summary_size = len(summary_resp.content)
    detailed_size = len(detailed_resp.content)
    assert summary_size < detailed_size, (
        f"summary ({summary_size} bytes) should be smaller than "
        f"detailed ({detailed_size} bytes)"
    )
